import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import PatientSource from './PatientContext'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

//Included PatientSource wrapper so that information is shared in the dashboard page and the other pages

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <PatientSource>
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </PatientSource>
  )
}
